INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\venv\Lib\site-packages\typing_extensions.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\clubs\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\clubs\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\clubs\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\forms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /faculty/update_faculty_sl/2
Traceback (most recent call last):
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\views.py", line 107, in update_faculty_serial_number
    return redirect('faculty_list')  # Redirect to the faculty list page or any other page
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Durjoy\PycharmProjects\uap_cse\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'faculty_list' not found. 'faculty_list' is not a valid view function or pattern name.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\faculty\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Durjoy\PycharmProjects\uap_cse\uap_cse\views.py changed, reloading.
